---
type: Minor
name: Environmental Studies
code: ENV
urls: 
- https://ua.princeton.edu/fields-study/minors/environmental-studies
- https://environment.princeton.edu/education/program-in-environmental-studies/req-courses
contacts:
- type: Director
  name: Corina E. Tarnita
  email: ctarnita@princeton.edu
description: |-
  For more than 30 years, the Program in Environmental Studies (ENV), now based in the High Meadows Environmental Institute (HMEI), has aimed to equip Princeton students with the skills to address critical environmental challenges that they will face throughout their careers and in life. Our guiding ethos is grounded in the appreciation that environmental challenges — both present and future — cannot be solved by any one discipline alone, but require concerted, multidisciplinary and interdisciplinary efforts, spanning all four divisions of the university. To that end, the program is designed to attract students from all disciplinary backgrounds and with varied interests, and to allow them to tailor their learning while also ensuring that they are exposed to fundamental environmental questions and methods/approaches through a variety of complementary lenses. In that sense, the ENV certificate — and, if approved, the minor — is designed to complement majors and not overlap or compete with them: specifically, it aims to provide a much broader multidisciplinary lens than any individual department or even individual division could.
max_common_with_major: 1
declaration_limit: 5
double_counting_allowed: true
req_list:
- name: Program of Study
  min_needed: ALl
  explanation: |-
    The Minor in Environmental Studies is open to students concentrating in any academic discipline and designed for students seeking a broad, multidisciplinary and interdisciplinary introduction to environmental topics. To be eligible for the minor, students are required to complete two (2) foundational courses, at least one of which is at or above the 300 level, and three (3) elective courses, at least two of which are at or above the 300 level. Two of the total five (5) courses must be in humanities and/or social sciences and two must be in natural sciences and engineering. No more than one (1) course filling the requirement for the ENV minor may also be counted toward the student's departmental concentration or another minor/certificate. 
  req_list:
  - name: Foundational Courses
    min_needed: 2
    req_list:
    - name: Below 300 Level
      min_needed: 0
      max_counted: 1
      course_list: 
      - ENV 200
      - ENV 210
      - ENV 238
      - GEO 102
    - name: Above 300 Level
      min_needed: 1
      max_counted: ALL
      course_list: 
      - ENV 303
      - ENV 304
      - ENV 343
      - ENV 354
      - ENV 363
      - ENV 367
      - ENV 377
      - CEE 306
      - CEE 334
      - CEE 344
      - CEE 321
      - CHV 321
      - EEB 308
      - EEB 321
      - EEB 417
      - GEO 360
      - GEO 362
      - GEO 366
      - HIS 394
      - SPI 306
      - SPI 350
      - SPI 405
  - name: Elective Courses
    min_needed: 3
    req_list:
    - name: Below 300 Level
      max_counted: 1
      min_needed: 0
      course_list: 
      - ENV 204
      - ENV 212
      - ENV 251
      - ANT 214
      - ANT 219
      - ANT 245
      - ARC 205
      - CEE 207
      - CLA 226
      - CLA 247
      - ENE 202
      - FRE 230
      - GEO 202
    - name: Above 300 Level
      max_counted: ALL
      min_needed: 2
      course_list:
      - ENV 302
      - ENV 305
      - ENV 310
      - ENV 316
      - ENV 327
      - ENV 330
      - ENV 345
      - ENV 347
      - ENV 353
      - ENV 357
      - ENV 363
      - ENV 380
      - ENV 381
      - ENV 385
      - ENV 428
      - ENV 448
      - ENV 455
      - ENV 460
      - ENV 551
      - ENV 596
      - AMS 304
      - AMS 354
      - AMS 403
      - AMS 415
      - AMS 419
      - ANT 322
      - ANT 364
      - ANT 387
      - ANT 443
      - ANT 446
      - ANT 452
      - ARC 492
      - ART 484
      - CEE 304
      - CEE 306
      - CEE 334
      - CEE 392
      - CEE 401
      - CEE 474
      - CEE 518
      - CEE 571
      - CEE 586
      - CEE 587
      - CHM 544
      - ECO 355
      - ECS 378
      - ECS 389
      - ECS 489
      - ENE 318
      - ENE 321
      - ENE 372
      - ENE 431
      - ENG 384
      - FRE 338
      - FRE 420
      - GEO 360
      - GEO 361
      - GEO 363
      - GEO 366
      - GEO 369
      - GEO 370
      - GEO 376
      - GEO 416
      - GEO 435
      - GEO 470
      - GEO 561
      - GER 521
      - GER 523
      - GER 530
      - GHP 413
      - GLS 340
      - HIS 412
      - HIS 432
      - MAE 328
      - MAE 463
      - MUS 334
      - NES 366
      - POL 586
      - POR 407
      - SAS 355
      - SOC 377
      - STC 349
      - THR 386
      - URB 304
      - VIS 324
- name: Breadth
  min_needed: ALL
  req_list:
  - name: Humanities and Social Sciences
    min_needed: 2
    course_list:
    - ENV 200A
    - ENV 200C
    - ENV 200E
    - ENV 238
    - ENV 304
    - ENV 343
    - ENV 363
    - ENV 377
    - CHV 321
    - HIS 394
    - SPI 306
    - SPI 350
    - SPI 405
    - ENV 204
    - ENV 251
    - ENV 305
    - ENV 310
    - ENV 316
    - ENV 327
    - ENV 345
    - ENV 347
    - ENV 357
    - ENV 363
    - ENV 380
    - ENV 381
    - ENV 428
    - ENV 448
    - ENV 455
    - ENV 460
    - ENV 596
    - AMS 304
    - AMS 354
    - AMS 403
    - AMS 415
    - AMS 419
    - ANT 214
    - ANT 219
    - ANT 245
    - ANT 322
    - ANT 364
    - ANT 387
    - ANT 443
    - ANT 446
    - ANT 452
    - ARC 205
    - ARC 492
    - ART 484
    - CEE 392
    - CLA 226
    - CLA 247
    - ECO 355
    - ECS 378
    - ECS 389
    - ECS 489
    - ENG 384
    - FRE 230
    - FRE 338
    - FRE 420
    - GER 521
    - GER 523
    - GER 530
    - GHP 413
    - HIS 412
    - HIS 432
    - MUS 334
    - NES 366
    - POL 586
    - POR 407
    - SAS 355
    - SOC 377
    - STC 349
    - THR 386
    - URB 304
    - VIS 324
  - name: Natural Sciences and Engineering
    min_needed: 2
    course_list:
    - ENV 200B
    - ENV 200D
    - ENV 200F
    - ENV 210A
    - ENV 210B
    - ENV 303
    - ENV 304
    - ENV 343
    - ENV 354
    - ENV 367
    - ENV 377
    - CEE 306
    - CEE 334
    - CEE 344
    - EEB 308
    - EEB 321
    - EEB 417A
    - EEB 417B
    - GEO 102A
    - GEO 360
    - GEO 362
    - GEO 366
    - SPI 350
    - SPI 405
    - ENV 212
    - ENV 302
    - ENV 305
    - ENV 330
    - ENV 353
    - ENV 385
    - ENV 551
    - CEE 207
    - CEE 304
    - CEE 306
    - CEE 334
    - CEE 392
    - CEE 401
    - CEE 474
    - CEE 518
    - CEE 571
    - CEE 586
    - CEE 587
    - CHM 544
    - ENE 202
    - ENE 318
    - ENE 321
    - ENE 372
    - ENE 431
    - GEO 202
    - GEO 360
    - GEO 361
    - GEO 363
    - GEO 366
    - GEO 369
    - GEO 370
    - GEO 376
    - GEO 416
    - GEO 435
    - GEO 470
    - GEO 561
    - GLS 340
    - MAE 328
    - MAE 463
    - STC 349
- name: Independent Work
  explanation: |-
    Students must investigate an environmental topic as a component of their independent work, which can take one of four forms:
    1. a substantial part (e.g., a chapter) of a senior thesis.
    2. a junior paper submitted to fulfill departmental requirement; supervising faculty needs to attest to its ENV focus.
    3. a 15-20-page final report based on work done (at any stage of undergrad career) during an HMEI internship supervised by a University faculty member. The supervising faculty must review and sign off on the paper as being of sufficient quality to satisfy an independent paper requirement (e.g., a JP).
    4. a 15-20-page independent paper supervised and approved by an HMEI or HMEI-affiliated faculty.
    In all these instances, when the supervising faculty is in doubt about whether the environmental focus is sufficient to satisfy the minor requirement, the student needs to reach out to the ENV program director to obtain approval prior to embarking on the work.
  iw_relationship: hybrid
  no_req: 